version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./todoListLaravelReactApp:/app
    depends_on:
      - db
    stdin_open: true # docker run -i
    tty: true        # docker run -t

  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_DB: todoappdb
      POSTGRES_USER: tododbuser
      POSTGRES_PASSWORD: root
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
      
    volumes:
      - ./storage/dbdata:/usr/local/Cellar/postgresql/14.0
    ports:
      - 5432:5432